Numpy Practice

In [3]:
import numpy as np

In [4]:
one_dimensional_array=np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])
print(one_dimensional_array)

[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]


In [5]:
two_dimensional_array=np.array([[1,2],[3,4],[5,6],[7,8]])
print(two_dimensional_array)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [7]:
array_populated_with_zeros=np.zeros((2,3))
print(array_populated_with_zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
array_populated_with_ones=np.ones((2,3))
print(array_populated_with_ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [10]:
sequence_of_numbers=np.arange(5,12)
print(sequence_of_numbers)

[ 5  6  7  8  9 10 11]


In [15]:
populate_array_with_random_nums_between_50_and_100_1d=np.random.randint(low=50,high=100,size=(5))
populate_array_with_random_nums_between_50_and_100_2d=np.random.randint(low=50,high=100,size=(5,5))
print(populate_array_with_random_nums_1d,"\n\n",populate_array_with_random_nums_2d)

[53 74 54 52 89] 

 [[59 60 56 55 91]
 [67 98 81 92 51]
 [82 94 60 64 53]
 [53 92 83 95 51]
 [94 88 79 88 94]]


In [13]:
random_floats_between_0_and_1=np.random.random([10])
print(random_floats_between_0_and_1) 

[0.65020743 0.86144392 0.05306121 0.18556286 0.80480439 0.87004519
 0.04922465 0.2866943  0.15732893 0.7676009 ]


Mathematical Operations on NumPy Operands
If you want to add or subtract two arrays, linear algebra requires that the two operands have the same dimensions. Furthermore, if you want to multiply two arrays, linear algebra imposes strict rules on the dimensional compatibility of operands. Fortunately, NumPy uses a trick called broadcasting to virtually expand the smaller operand to dimensions compatible for linear algebra. For example, the following operation uses broadcasting to add 2.0 to the value of every item in the array created in the previous code cell:

In [14]:
random_floats_between_2_and_3=random_floats_between_0_and_1+2.0
print(random_floats_between_2_and_3)

[2.65020743 2.86144392 2.05306121 2.18556286 2.80480439 2.87004519
 2.04922465 2.2866943  2.15732893 2.7676009 ]


In [17]:
populate_array_with_random_nums_between_150_and_300_1d=populate_array_with_random_nums_between_50_and_100_1d*3
print(populate_array_with_random_nums_between_150_and_300_1d)

[264 177 270 201 153]


create a simple dataset consisting of a single feature and a label as follows:

Assign a sequence of integers from 6 to 20 (inclusive) to a NumPy array named feature.

Assign 15 values to a NumPy array named label such that:1

In [21]:
feature=np.arange(6,21)
print(feature)
label=(feature*3)+4
print(label)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


To make your dataset a little more realistic, insert a little random noise into each element of the label array you already created. To be more precise, modify each value assigned to label by adding a different random floating-point value between -2 and +2.

Don't rely on broadcasting. Instead, create a noise array having the same dimension as label.

In [23]:
noise =np.random.randint(low=-2,high=2,size=len(label))
print(noise)
label+=noise
print(label)

[ 1  0  0 -2 -2  1  1 -2 -1  0  0 -1 -1 -2  1]
[23 25 28 29 32 38 41 41 45 49 52 54 57 59 65]
